# file: C:\Users\rcasa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\_core\_exceptions.py
# hypothesis_version: 6.135.17

[1000, 1024, 'EiB', 'GiB', 'KiB', 'MiB', 'PiB', 'TiB', 'bytes']